FROM golang:1.7.3-alpine

RUN apk update && apk add git make

WORKDIR /go/src/github.com/madhu1512/ecs-gen

# to statically link
ENV CGO_ENABLED 0
CMD go get -u github.com/Masterminds/glide && make build
